@OpsBoard_API_HostAddress = http://localhost:5162

GET {{OpsBoard_API_HostAddress}}/api/resource
Accept: application/json

###

POST {{OpsBoard_API_HostAddress}}/api/resource
Content-Type: application/json

{
	"name": "Laptop",
	"type": "Hardware",
	"organizationId": 1
}

###
